### ISSUE TITLE
Shopwing as Empty but app seeing accurate temperature 

### ISSUE THREAD

**Issue by uratrtl** [matthewnitschke/ember-macos#44] opened 2024-10-04 14:43 UTC
Ember Mate is showing as empty, but when I check the app, it is reading the temperature fine. I've tried closing and reopening the app and disconnecting and reconnecting, but it still shows as empty. Should I try forgetting the mug in bluetooth from my Mac?

<img width="316" alt="image" src="https://github.com/user-attachments/assets/380fc4f4-2d55-41fd-a110-b6ffe11030d4">

![image](https://github.com/user-attachments/assets/459f8668-7314-461c-b022-eef777d60f98)

**Comment by matthewnitschke** [comment] 2024-10-05 19:32
The mug itself has a limitation where it can be connected to a single client at once

Have you tried "forgetting" it from all devices, and then re-connecting it to EmberMate?

**Comment by uratrtl** [comment] 2024-10-12 16:31
Weirdly they both connect as long as the other official ember app is running on the same computer, I dont even use the phone app at all 
![image](https://github.com/user-attachments/assets/2c422743-710a-4593-b197-2de3bb9e4650)

Im starting to think its some wonkiness with the mug itself, I tried giving it a good scrubbing and it seems to be behaving itself better now, but not always.

**Comment by matthewnitschke** [comment] 2024-10-16 00:55
I guess that makes sense, the mug can only connect to a single device, and in your instance its still a single device (as in bluetooth client)

I'm not sure what specifically is going on, its fairly consistent on my end

If you feel like the issue is persisting, feel free to re-open another issue, otherwise I'll go ahead and close this one

**Closed as completed by matthewnitschke** 2024-10-16 00:55 UTC

**Comment by uratrtl** [comment] 2024-10-16 00:57
Thank you, love the app! I think its probably my particular mug, but when I first encountered this, I was baffled
